In [1]:
3-2 

[1] 1

In [2]:
sin(4)

[1] -0.7568025

In [3]:
4>3

[1] TRUE

In [4]:
4==4

[1] TRUE

In [5]:
!(4==4)

[1] FALSE

In [6]:
(4==4) && (3>12)

[1] FALSE

In [7]:
(4==4) && (3<12)

[1] TRUE

In [8]:
# Variable Assignment

In [9]:
a <- 3+3

In [10]:
greetings <- "Hey, Buddy!"

In [11]:
print(greetings)

[1] "Hey, Buddy!"


In [12]:
some_logic <- TRUE

In [13]:
#The Vector

In [14]:
dat <- c(4,5,6,23,2)

In [15]:
print(dat)

[1]  4  5  6 23  2


In [16]:
v1 <- c(1,2,3)
v2 <- c(5,4,3)
v <- c(v1,v2)

In [17]:
print(v)

[1] 1 2 3 5 4 3


In [18]:
v3 <- seq(-10,10,2)

In [19]:
print(v3)

 [1] -10  -8  -6  -4  -2   0   2   4   6   8  10


In [20]:
print(v3)

 [1] -10  -8  -6  -4  -2   0   2   4   6   8  10


In [21]:
m <- seq(1:20)

In [22]:
print(m)

 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20


In [23]:
u <- seq(-2:2)

In [24]:
print(u)

[1] 1 2 3 4 5


In [25]:
u <- (-2:2)

In [26]:
print(u)

[1] -2 -1  0  1  2


In [27]:
w <- seq(-2,2)

In [28]:
print(w)

[1] -2 -1  0  1  2


In [29]:
v <- rnorm(5)

In [30]:
v

[1]  1.8792896  0.5831229  1.5589951 -0.7261834  0.5667679

In [31]:
v[2:5]

[1]  0.5831229  1.5589951 -0.7261834  0.5667679

In [32]:
v[c(1,3)]

[1] 1.879290 1.558995

In [33]:
u <- c(5,6,8,22)

In [34]:
u[1] <- 0

In [35]:
print(u)

[1]  0  6  8 22


In [36]:
u3 <- u[1:3]

In [37]:
print(u3)

[1] 0 6 8


In [38]:
#A problem he gave us in class

In [39]:
v <- c(10,20,30)

In [40]:
v[1] <- 0

In [41]:
v[2] <- 0

In [42]:
print(v)

[1]  0  0 30


In [43]:
#a different way to solve this

In [44]:
t <- c(10,20,30)
t[1:2] <- 0
print(t)

[1]  0  0 30


In [45]:
#Create a vector (call it v1) with the five elements 10, 20, 30, 40, and 50. Now use indexing to get the first, third, and fifth elements from that vector and put them in a new vector (call that one v2)

In [46]:
v1 <- seq(10,50,10)

In [47]:
print(v1)

[1] 10 20 30 40 50


In [48]:
v2 <- v1[1] && v1[3] && v1[5]

In [49]:
print(v2)

[1] TRUE


In [50]:
#answer

In [51]:
v1 <- c(10,20,30,40,50)

In [52]:
idx <- c(1,3,5)

In [53]:
v2 <- v1[idx]

In [54]:
print(v2)

[1] 10 30 50


In [55]:
#Another approach

In [56]:
v1 <- seq(10,50,10)  #this is creating a vector
idx <- c(TRUE,FALSE,TRUE,FALSE,TRUE)  #
v2 <- v1[idx]
print(v2)

[1] 10 30 50


In [57]:
#Another approach

In [58]:
v1 <- seq(10,50,10)  
v2 <- c(v[1],v[3],v[5])
print(v2)

[1]  0 30 NA


In [59]:
print("hi")

[1] "hi"


In [60]:
v1 > 50

[1] FALSE FALSE FALSE FALSE FALSE

In [61]:
print(v1)

[1] 10 20 30 40 50


In [62]:
#Useful operations on vectors

In [63]:
v <- rnorm(10)

In [65]:
n <- length(v)

In [66]:
print(n)

[1] 10


In [67]:
#The Matrix

In [68]:
x1 <- c(4,5,6)
x2 <- c(55,55,77)

In [69]:
m <- cbind(x1,x2)

In [70]:
print(m)

     x1 x2
[1,]  4 55
[2,]  5 55
[3,]  6 77


In [71]:
o <- rbind(x1,x2)

In [72]:
print(o)

   [,1] [,2] [,3]
x1    4    5    6
x2   55   55   77


In [78]:
a <- matrix(0, nrow=5, ncol=3)

In [79]:
print(a)

     [,1] [,2] [,3]
[1,]    0    0    0
[2,]    0    0    0
[3,]    0    0    0
[4,]    0    0    0
[5,]    0    0    0


In [80]:
dat <- rnorm(15)

In [81]:
b <- matrix(dat, ncol=3)

In [82]:
print(b)

          [,1]        [,2]        [,3]
[1,] 1.2620986 -0.67317627 -1.42485428
[2,] 0.3353611 -1.30722390 -1.13677674
[3,] 1.3021973  0.04305632 -0.91825807
[4,] 0.2611859  1.97254986  1.32501845
[5,] 0.3106259 -0.22200940  0.02385126


In [83]:
#indexing matrices

In [84]:
dat <- sample(12)

In [85]:
m <- matrix(dat, ncol=3)

In [86]:
print(m)

     [,1] [,2] [,3]
[1,]    5    9   12
[2,]    7    4    2
[3,]   10    3    6
[4,]    8   11    1


In [87]:
m[2,3]

[1] 2

In [88]:
is.matrix(m)

[1] TRUE

In [89]:
str(m)

 int [1:4, 1:3] 5 7 10 8 9 4 3 11 12 2 ...


In [94]:
miranda <- matrix("heck", nrow=10, ncol=11)

In [96]:
print(miranda)

      [,1]   [,2]   [,3]   [,4]   [,5]   [,6]   [,7]   [,8]   [,9]   [,10] 
 [1,] "heck" "heck" "heck" "heck" "heck" "heck" "heck" "heck" "heck" "heck"
 [2,] "heck" "heck" "heck" "heck" "heck" "heck" "heck" "heck" "heck" "heck"
 [3,] "heck" "heck" "heck" "heck" "heck" "heck" "heck" "heck" "heck" "heck"
 [4,] "heck" "heck" "heck" "heck" "heck" "heck" "heck" "heck" "heck" "heck"
 [5,] "heck" "heck" "heck" "heck" "heck" "heck" "heck" "heck" "heck" "heck"
 [6,] "heck" "heck" "heck" "heck" "heck" "heck" "heck" "heck" "heck" "heck"
 [7,] "heck" "heck" "heck" "heck" "heck" "heck" "heck" "heck" "heck" "heck"
 [8,] "heck" "heck" "heck" "heck" "heck" "heck" "heck" "heck" "heck" "heck"
 [9,] "heck" "heck" "heck" "heck" "heck" "heck" "heck" "heck" "heck" "heck"
[10,] "heck" "heck" "heck" "heck" "heck" "heck" "heck" "heck" "heck" "heck"
      [,11] 
 [1,] "heck"
 [2,] "heck"
 [3,] "heck"
 [4,] "heck"
 [5,] "heck"
 [6,] "heck"
 [7,] "heck"
 [8,] "heck"
 [9,] "heck"
[10,] "heck"


In [97]:
# The 'Data Frame'

In [102]:
id <- seq(4)
score <- rnorm(4)
names <- c("john", "paul", "george", "ringo")
vocals <- c(TRUE, TRUE, FALSE, FALSE)
dset <- data.frame(id, names, score, vocals)

In [103]:
print(dset)

  id  names      score vocals
1  1   john  0.3471010   TRUE
2  2   paul  1.6092726   TRUE
3  3 george -1.3422567  FALSE
4  4  ringo -0.6495523  FALSE


In [104]:
dset[1,2]

[1] john
Levels: george john paul ringo